#!/usr/bin/env python2
# -*- coding: utf-8 -*-

import sys

#Creating tuples containing the line, the number corresponding to it and the line number 
cf=0
f=list()
n=int(sys.argv[1])
for line in sys.stdin:
	cf+=1
	if len(line)>1:
		ns=[int(s) for s in line.split() if s.isdigit()]
		variable=[line,ns[0]]
		variable.append(cf)
		f.append(variable)


#Sorting the tuples by the numbers corresponding to the lines 
final=sorted(f, key=lambda data: data[1], reverse=True)

final[0].append(1)
length=len(final)
i=1
for i in range (1,length):
	prev_rank=final[(i-1)]
	cur_rank=final[i]
	if cur_rank[1]!=prev_rank[1]:
		cur_rank.append(i+1)
	else:
		cur_rank.append(prev_rank[3])
	i+=1

for k in final:
	if k[3]<=n:
		print(k[0].rstrip('\n'))
